### PR TITLE
Nominate Jaime Magiera for Maintainer

### PR DESCRIPTION
**Pull request by christianh814**
Nominate @JaimeMagiera for Maintainer

Context #107 

Signed-off-by: Christian Hernandez <christian@codefresh.io>

### CODE REVIEW

**Comment by christianh814** [comment]
+1 Binding

**Comment by JaimeMagiera** [comment]
1. I've promoted the values in various media outlets, both in presentations, interviews, and my own radio show. I've instilled those values in dozens of developers at my day job (the work of which has been presented publicly) 

2. I have extensive experience managing/leading Working Groups and Working Group resources (e.g. OKD Working Group), including pull requests of various kinds. 

3. Brought to the table the Sustainability Working Group formation and suggested ways in which we can cooperate. I've been attending those meetings as well. 

Those are a few examples.

**Comment by nikimanoledaki** [comment]
Jaime has brought a lot of ideas for the environmental sustainability whitepaper that we're creating as part of OpenGitOps. He has been invaluable to moving the project move forward. He has also been facilitating conversations on GitOps and the whitepaper in the Environmental Sustainability WG as well.

**Review by scottrigby — APPROVED** [review]
Yes I think this would be very helpful. Thank you @JaimeMagiera !

**Comment by todaywasawesome** [comment]
+1 Binding

**Comment by chris-short** [comment]
+1 binding

**Review by todaywasawesome — APPROVED** [review]

**Comment by todaywasawesome** [comment]
As per governance, 3/5 vote is reached and Jamie is approved!

**Pull request merged**
