### PR TITLE
Nominate Roberth Strand for Maintainer

### PR DESCRIPTION
**Pull request by christianh814**
Nomination of @roberthstrand as maintainer

Context #107 

Signed-off-by: Christian Hernandez <christian@codefresh.io>

### CODE REVIEW

**Comment by roberthstrand** [comment]
As mentioned in the [slack thread](https://cloud-native.slack.com/archives/C01G9DEE88M/p1655709791226539?thread_ts=1655500442.759949&cid=C01G9DEE88M), I would like to summarize why I would be a good fit as a maintainer.

I got long experience from the GitOps Working Group, and the OpenGitOps project. I started when the group was really young, and was part of the process of defining the GitOps Principles. Furthermore, I have been in the program committee for two GitOpsCon, have personally spoken at several events about what GitOps is and how to implement it, as well as represented the OpenGitOps project on videos for the likes of Microsoft.

**Comment by joshgav** [comment]
+1 nb

**Comment by todaywasawesome** [comment]
> +1
> 
> But, as I’m stepping down I’m requesting @scottrigby or @todaywasawesome be the final approval authority.

Just a clarification, as per governance, adding additional maintainers requires a super majority vote from maintainers. We are working on updating governance ATM but I don't think that part will change.

**Comment by christianh814** [comment]
+1 Binding

**Review by scottrigby — APPROVED** [review]
+1 binding

I think @roberthstrand is ready to be a maintainer based on the list of responsibilities outlined under "Maintainers" in the OpenGitOps Governance https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#maintainers. As a reminder, we should all remember to consult this doc for all decisions.

**Comment by todaywasawesome** [comment]
+1 binding

**Review by todaywasawesome — APPROVED** [review]

**Comment by todaywasawesome** [comment]
As per governance, a 3/5 maintainers have voted yay, the motion passes.

**Pull request merged**
