### PR TITLE
Moshe requesting to become a maintainer

### PR DESCRIPTION
**Pull request by moshloop**

### CODE REVIEW

**Comment by moshloop** [comment]
@chrispat @chris-short @todaywasawesome @murillodigital  @scottrigby @csand-msft

**Comment by chris-short** [comment]
@moshloop Can you run a `git commit --amend --no-edit --signoff` and push again, please?

**Review by todaywasawesome — CHANGES_REQUESTED** [review]
Appreciate the interest. Moshe has helped out with the standards and been present in some meetings but at this point I'd like to see more steady and consistent contributions to the project before I would consider him for becoming a maintainer. 

There is no shortage of work to be done.

**Comment by moshloop** [comment]
@todaywasawesome - I have been present in the vast majority of meetings and my name has been on pretty much every single non-trivial commit/pr to documents which is the primary output of this group?

**Comment by scottrigby** [comment]
@moshloop I second what @todaywasawesome said, and suggest waiting a bit on this.

However I wanted to say I really appreciate in Today's WG meeting you taking responsibility for your part in past meeting inefficiency (principals committee). To me, that goes a long way. None of us are perfect (including myself of course!), and to me what matters all of us improving what we can to work together well as a group, make a smoother path for everyone to contribute appropriately, and to help move the project forward to reach next milestones. You do offer a lot to the group, and I'm glad you're part of it. I would also like to see you accept and work with maintainer feedback on PRs, and help us keep the scope contained for each issue – for example completing https://github.com/open-gitops/website/pull/16, and even contributing to fix the maintainers section of the website according to the agreed upon plan here https://github.com/open-gitops/website/issues/22#issuecomment-936996695 (this issue https://github.com/open-gitops/website/issues/56 is meant to track part of this work to be done, but we may also need to expand that or make additional issues to track the rest of the agreed solution, and link them all together). And ultimately, that work needs to be done. I can pitch in to that too, in priority with other goals.

Currently new maintainers are decided upon by existing maintainers according to project governance. However – to make criteria more clear – I would like to see anyone wanting to help maintain the project consistently practice the appropriate parts of the documented maintainer responsibilities as outlined in https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#maintainers. @moshloop I would love it for you to continue the above for a time, and circle back on this whether or not I am still a maintainer at that time.

I hope this is taken in the friendly and team spirit I mean it. It is also not my call alone. This is just my point of view at this time. I am also open to talking about this together, privately or publicly, in whatever way makes the most sense to you.

**Comment by moshloop** [comment]
@scottrigby The evidence of my continued contribution says otherwise, I have more contributions than 3 of the existing maintainers

Screenshot 2022-01-19 at 22 43 30

https://gitopswg.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1

**Comment by scottrigby** [comment]
@moshloop I'm very interested in your past and continued contribution. Again, my point of view at this time does not debate your contributions at all. I also do not see this as a competition in any way, and recognize there are multiple ways to contribute to this project in addition to git commits.

To keep it a it shorter this time, I think it is important to hold space for differences of opinion, and I believe the WG and project has has proven we do that. However my personal opinion is that all potential new maintainers should demonstrate working well together with the group, listening to and working with feedback etc, in order to maintain a safe space for other people with equally important things to offer to be able to contribute as well. I think we are getting there, but I personally would like to see that happen more consistently for a time while we work on and complete another milestone - because this is where the friction came before.

I hope This is coming across clearly. I am trying to be both honest and polite, while also acknowledging the value of your contributions.

**Comment by scottrigby** [comment]
@moshloop thanks for meeting with me, I'm happy to do that again too. I have updated the comment above that you did not feel was clear. 

Again, I am only one of 7 maintainers. These comments are part of the consensus process here – as outlined in the project [Decision Making](https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#decision-making) process.

Are you satisfied to close this PR at this time, or would you rather we continue the consensus process here? There is no maintainer disagreement on this so far. I think there is a good path forward and I would prefer to do that and revisit, but if you prefer I am not opposed to calling a vote. Note that [ading additional maintainers requires a supermajority](https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#supermajority-decisions) if a vote is called.

**Pull request closed without merging**
