### PR TITLE
nominate Niki Manoledaki for Maintainer

### PR DESCRIPTION
**Pull request by niklasmtj**
Hereby I want to nominate @nikimanoledaki as a maintainer. She's doing a lot of great work in the group and is also leading the group's environmental sustainability subgroup.

Will add an email when I got one.

### CODE REVIEW

**Review by roberthstrand — APPROVED** [review]
Yes! 👏

**Comment by chris-short** [comment]
+1 * 💯

**Comment by christianh814** [comment]
+1 👏

**Comment by williamcaban** [comment]
+1

**Comment by hongchaodeng** [comment]
LGTM +1

**Comment by JaimeMagiera** [comment]
+1

**Comment by todaywasawesome** [comment]
Yes! Let's go! +1

**Pull request merged**
