### PR TITLE
Nominate William Caban for Maintainer

### PR DESCRIPTION
**Pull request by christianh814**
Nomination for @williamcaban to be a Maintainer

Context #107 

Signed-off-by: Christian Hernandez <christian@codefresh.io>

### CODE REVIEW

**Comment by joshgav** [comment]
+1 nb

**Comment by christianh814** [comment]
+1 Binding

**Comment by scottrigby** [comment]
@williamcaban  or @nikimanoledaki – would one of you mind outlining why folks should vote William to be an OpenGitOps maintainer? Because others have requested and have not been approved for the time being, we want to make sure this is a fair process. Thanks!

As a reminder, we should refer to the list of responsibilities outlined under "Maintainers" in the OpenGitOps Governance https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#maintainers for this and all decisions by the group of maintainers.

**Comment by nikimanoledaki** [comment]
William is an active and committed member of the group who actively creates inclusive spaces and promotes GitOps tools, practices, and patterns. He has [written](https://www.redhat.com/en/blog/role-orchestrator-gitops-driven-operations) about GitOps and done talks such as [this one as part of Cloud Native Guatemala](https://www.youtube.com/watch?v=atcaaMpC2Hg).

I appreciate our continued discussions and efforts to make the environmental sustainability whitepaper happen as well as the conversations on GitOps in the Environmental Sustainability WG. 🙌 🌱

**Comment by christianh814** [comment]
I also like to add that William helped with the Spanish translation of the Principles

https://github.com/open-gitops/documents/pull/59

**Comment by todaywasawesome** [comment]
+1 Binding

**Comment by chris-short** [comment]
+1 binding

**Review by todaywasawesome — APPROVED** [review]

**Comment by todaywasawesome** [comment]
3/5 vote being reached, it passes. Congrats!

**Pull request merged**
