### PR TITLE
Nomination for Maintainers

### PR DESCRIPTION
**Pull request by christianh814**
Remove stale maintainers nominate potential maintainers

- [x] @williamcaban 
- [x] @niklasmtj 
- [x] @JaimeMagiera 
- [x] @roberthstrand

Nominated maintainers need to agree to be added as a maintainers. Please review the responsibilities of the [maintainers](https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#maintainers) 

Once nominees have accepted their nomination I will open this up for review by the co-chairs.

Signed-off-by: Christian Hernandez <christianh814@users.noreply.github.com>

### CODE REVIEW

**Comment by chris-short** [comment]
@christianh814 and I were having a biweekly sync and we realized the MAINTAINERS file could use a refresh. We came up with this initial group of folks based off their participation in the ecosystem, our meetings, and other work in the community.

**Comment by williamcaban** [comment]
I accept the nomination.

**Comment by JaimeMagiera** [comment]
I accept the nomination.

**Review by nishadmehendale — APPROVED** [review]
LGTM

**Comment by christianh814** [comment]
@todaywasawesome @scottrigby and/or @chris-short PTAL (or we can discuss next working group meeting)

**Review by roberthstrand — APPROVED** [review]
I would be honored 🖖

**Review by christianh814 — COMMENTED** [review]
+1

**Review by chris-short — APPROVED** [review]
Approved

**Comment by scottrigby** [comment]
@chris-short @christianh814 Glad you two got to meet, and I agree @williamcaban, @niklasmtj, @JaimeMagiera and @roberthstrand all feel like natural fits given group participation, including recent months. 

I'm sure there are others in the group who would be a good fit for OpenGitOps maintainers too. 

As a reminder, new maintainers can be nominated and voted on by existing maintainers at any point. However, as I understand it the reason for prioritizing this now is that @chris-short will be stepping down from his co-chair position in July, and new co-chairs must already be maintainers before the nomination process and vote for co-chairs is held.

@christianh814 would you mind sending an email to the mailing list letting folks know about this, so it's clear to those who couldn't make today's meeting and may not be fully updated on all PRs? (to be fair to everyone, we have had open PRs for much longer than this timeframe)

**Comment by scottrigby** [comment]
@christianh814  thinking on this more, we may want to make each of these additionally proposed maintainers as separate PR too. It would make sense to add a summary of what each person has brought to the GitOps WG and OpenGitOps project within each PR so that the process is fully transparent to everyone in the WG and project, and we don't accidentally fall into favoritism.

Also, I think removing maintainers due to inactivity is something that should definitely be a separate PR from adding new ones. This will allow proper time for decisions to be made for each of these. For example, it would give a separate space to hear from the existing maintainers who this PR is proposing removing, and there is no specific deadline for this.

**Comment by christianh814** [comment]
Per @scottrigby 's request. This has been broken out into individual PRs. I believe the votes still bind.

- Remove Inactive Maintainers: #108 
- William Caban Nomination: #109 
- Niklas Metje Nomination #110 
- Jaime Magiera Nomination  #111 
- Roberth Strand Nomination #112

**Comment by scottrigby** [comment]
Closing in favor of #109 #110 #111 & #112

**Pull request closed without merging**
