### PR TITLE
Update MAINTAINERS affiliations

### PR DESCRIPTION
**Pull request by scottrigby**
Hey @open-gitops/maintainers does this look right? LinkedIn says yes but checking with you all

- [x] @christianh814 
- [x] @JaimeMagiera 
- [x] @nikimanoledaki  confirmed over slack
- [x] @niklasmtj 
- [x] @roberthstrand 
- [x] @scottrigby 
- [x] @williamcaban

### CODE REVIEW

**Review by christianh814 — APPROVED** [review]
lgtm

**Review by williamcaban — COMMENTED** [review]
/lgtm

**Review by JaimeMagiera — APPROVED** [review]
LGTM

**Review by niklasmtj — APPROVED** [review]
🚀

**Review by roberthstrand — APPROVED** [review]
Correctamundo!

**Comment by scottrigby** [comment]
ok Niki confirmed over Slack so we're good to go. Thanks everyone 😄

**Pull request merged**
