### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by christianh814**
I am offering to volunteer as a maintainer. I have been an active member of the working group. I attend most of the meetings (see meeting notes for attendance verification), was a co-author of the GitOps Principles (and was part of that committee), and I am currently part of the events committee. Being part of the events committee, most of my time there is spent helping out with GitOps Con

### CODE REVIEW

**Review by scottrigby — APPROVED** [review]
+💯 from me. @christianh814 you have already been very helpful pitching in for many defined [maintainer responsibilities](https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#maintainers) and more. You have also shown – through consistent action – fairness, diplomacy, willingness to accept and work with feedback, willingness to take on unglamorous tasks in order to make priorities happen, desire to collaborate toward solving problems, ability to unblock others, and widespread promotion of GitOps principles and practices.

**Comment by chris-short** [comment]
+1000

**Comment by csand-msft** [comment]
+1

**Comment by todaywasawesome** [comment]
+1 binding 

@christianh814 your work in planning the events, and helping liaison with other projects has been invaluable.

**Comment by chris-short** [comment]
+1000

**Comment by chrispat** [comment]
+1

**Comment by murillodigital** [comment]
+1 @christianh814 you definitely deserve it!

**Pull request merged**
