### PR TITLE
Nominate Niklas Metje for Maintainer

### PR DESCRIPTION
**Pull request by christianh814**
Nominating @niklasmtj for Maintainer

Context #107 

Signed-off-by: Christian Hernandez <christian@codefresh.io>

### CODE REVIEW

**Comment by christianh814** [comment]
+1 Binding

**Comment by scottrigby** [comment]
@christianh814 or @nikimanoledaki – would one of you mind outlining why folks should vote Niklas to be an OpenGitOps maintainer? Because others have requested and have not been approved for the time being, we want to make sure this is a fair process. Thanks!

As a reminder, we should refer to the list of responsibilities outlined under "Maintainers" in the OpenGitOps Governance https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#maintainers for this and all decisions by the group of maintainers.

**Comment by niklasmtj** [comment]
Trying to sumarize why I would be a good choice as a maintainer. Even if I'm pretty new to the GitOps world I'm eager to learn but also teach about what GitOps is and why it is a great way to follow. I'm preparing a presentation about GitOps and the OpenGitOps principles which I would like to share on local meetups.
Also I'm super motivated to push this project forward and help finding its' place in the great landscape.

**Comment by christianh814** [comment]
I would like to add that Niklas has been very active in improving our website and is looking into importing other repos as a "source of truth" for the website

**Comment by chris-short** [comment]
+1 binding

**Review by todaywasawesome — APPROVED** [review]

**Comment by todaywasawesome** [comment]
As per governance, the vote passes. Congrats!

**Pull request merged**
