### PR TITLE
Update OpenGitOps project governance to reflect GitOps WG merging

### PR DESCRIPTION
**Pull request by scottrigby**
The GitOps Working Group is merging into the OpenGitOps project. This has been discussed for a long time, and was recently [agreed upon unanimously in Slack](https://cloud-native.slack.com/archives/C01G9DEE88M/p1708720298464849) that it's the right time to do this.

Maintainer reviews and merging of this PR to project Governance and related files constitutes the official merge. See https://github.com/open-gitops/project/blob/merge-gitops-wg-into-opengitops/GOVERNANCE.md for a preview.

## To-do

- [x] update the wg meeting documents to point to open gitops
    - see [OpenGitOps project meetings](https://docs.google.com/document/d/1hxifmCdOV5_FbKloDJRWZQHq0ge-trXJKF-BgV4wHVk/edit#heading=h.m1bztpjqh35d) doc
- [x] make a decision on the wg-gitops slack channel 
    - the decision has been made to move from #wg-gitops to #opengitops slack channel
- [ ] follow-up: point slack to #opengitops (or vice versa and rename)
    - There is an open CNCF Service Desk ticket to do that pending this PR being merged https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2204
- [ ] follow-up: update project home page with current status:
    - [ ] https://github.com/open-gitops
    - [ ] https://opengitops.dev
- [ ] follow-up: present to TAG App Delivery in May/June with an update on project status

## Additional info

- Currently this PR does not remove Chairs. This could be done in this PR if  desired by Maintainers or as a future follow-up.
- for previous history see: https://github.com/open-gitops/project/pull/123

### CODE REVIEW

**Review by christianh814 — APPROVED** [review]
LGTM!

**Review by niklasmtj — APPROVED** [review]
lgtm 🚀

**Review by roberthstrand — APPROVED** [review]

**Comment by JaimeMagiera** [comment]
lgtm

**Review by JaimeMagiera — APPROVED** [review]

**Review by todaywasawesome — APPROVED** [review]
Lets do it, thanks Scott!

**Comment by scottrigby** [comment]
With @williamcaban 's lgtm we have a supermajority of maintainers 🎉  Nice work everyone. The WG succeeded. Excited for the future of OpenGitOps 😄

**Pull request merged**
